Attribute VB_Name = "define_fields"
Option Explicit

Public Const LV_VIDEO_FILE = 0
Public Const LV_VIDEO_UID = 1
Public Const LV_VIDEO_TIMER = 2
Public Const LV_VIDEO_DURATION = 3
Public Const LV_VIDEO_VIDEO_CODEC = 4
Public Const LV_VIDEO_VIDEO_WIDTH = 5
Public Const LV_VIDEO_VIDEO_HEIGHT = 6
Public Const LV_VIDEO_VIDEO_FPS = 7
Public Const LV_VIDEO_VIDEO_BITRATE = 8
Public Const LV_VIDEO_AUDIO_CODEC = 9
Public Const LV_VIDEO_AUDIO_CHANNEL = 10
Public Const LV_VIDEO_AUDIO_HZ = 11
Public Const LV_VIDEO_AUDIO_BITRATE = 12
Public Const LV_VIDEO_PATH = 13

Public Const LV_CONVERTING_FILE = 0
Public Const LV_CONVERTING_UID = 1
Public Const LV_CONVERTING_PROCESS_HANDLE = 2
Public Const LV_CONVERTING_DURATION = 3
Public Const LV_CONVERTING_VIDEO_CODEC = 4
Public Const LV_CONVERTING_VIDEO_WIDTH = 5
Public Const LV_CONVERTING_VIDEO_HEIGHT = 6
Public Const LV_CONVERTING_VIDEO_FPS = 7
Public Const LV_CONVERTING_VIDEO_BITRATE = 8
Public Const LV_CONVERTING_AUDIO_CODEC = 9
Public Const LV_CONVERTING_AUDIO_CHANNEL = 10
Public Const LV_CONVERTING_AUDIO_HZ = 11
Public Const LV_CONVERTING_AUDIO_BITRATE = 12
Public Const LV_CONVERTING_PATH = 12
Public Const LV_CONVERTING_PASS_2 = 13
